# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='rank',
        ),
        migrations.AddField(
            model_name='document',
            name='len_of_doc',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index',
            name='freq',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
